name: Dependabot Whitelist
description: Check whitelisted dependencies.
inputs:
  whitelist:
    description: A whitelist of dependencies as a multi-line string with newline separator
    required: true
    default: ''
  dependencies:
    description: A comma-separated string of dependencies, e.g from dependabot/fetch-metadata outputs.dependency-names
    required: true
    default: ''
outputs:
  result:
    description: WHITELISTED <dependency> or BLOCKED <dependency>
runs:
  using: node12
  main: dist/index.js
