#!/bin/bash -e

# 1st arg (string) is the whitelist, newline-separated
# 2nd arg (string) is the dependencies to test, comma-separated
#
# Example usage:
# ./whitelist-check a\nb\nc a,c,d

# COLORS
RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'

if [[ -z "$1" ]]; then
  echo "Whitelist was empty"
  exit 1
fi

if [[ -z "$2" ]]; then
  echo "Dependencies was empty"
  exit 1
fi

# 1st arg
IFS=$'\n' read -rd '' -a WHITELIST <<<"$1"

# 2nd arg
IFS=',' read -ra DEPENDENCIES <<<"$2"

for DEP in "${DEPENDENCIES[@]}"; do

  # whitelist contains $DEP
  if (printf '%s\n' "${WHITELIST[@]}" | grep -xq "$DEP"); then
    echo -e "$GREEN WHITELISTED $NOCOLOR $DEP"
  else
    echo -e "$RED BLOCKED $NOCOLOR $DEP"
    exit 1
  fi

done
