name: Auto Merge dependabot
on: [ pull_request_target ]
permissions:
  pull-requests: write
  contents: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Only allow dependabot from this repo and not via forks
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./
        with:
          major: 'true'
          whitelist: |
            actions/checkout
            dependabot/fetch-metadata

      - run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
