name: CI
on: [ push, pull_request ]
jobs:
  test-script:
    runs-on: ubuntu-latest
    name: Tests the whitelist-check script
    steps:
      - uses: actions/checkout@v2.3.5

      - name: All dependencies are whitelisted
        env:
          whitelist: |-
            a
            b
            c
          dependencies: a,b
        run: ./whitelist-check ${{ env.whitelist }} ${{ env.dependencies }}

      - name: One dependency is not whitelisted
        run: |
          ./whitelist-check a\nb\nc a,c,d || exit_code=$?
          if [[ ${exit_code} -ne 1 ]]; then exit 1; fi

      - name: Empty whitelist returns exit 1
        run: |
          ./whitelist-check '' a,c,d || exit_code=$?
          if [[ ${exit_code} -ne 1 ]]; then exit 1; fi

      - name: Empty depdencencies returns exit 1
        run: |
          ./whitelist-check a\nb\nc '' || exit_code=$?
          if [[ ${exit_code} -ne 1 ]]; then exit 1; fi
