name: CI
on: [ push, pull_request ]
jobs:
  test-script:
    runs-on: ubuntu-latest
    name: Tests the whitelist-check script
    steps:
      - uses: actions/checkout@v2.3.5

      - name: All dependencies are whitelisted
        run: bash whitelist-check '${{ env.whitelist }}' '${{ env.dependencies }}'
        env:
          whitelist: |-
            a
            b
            c
          dependencies: a,b

      - name: One dependency is not whitelisted
        run: |
          bash whitelist-check '${{ env.whitelist }}' '${{ env.dependencies }}' || exit_code=$?
          if [[ ${exit_code} -ne 1 ]]; then exit 1; fi
        env:
          whitelist: |-
            a
            b
            c
          dependencies: a,c,d

      - name: Empty whitelist returns exit 1
        run: |
          bash whitelist-check ${{ env.whitelist }} '${{ env.dependencies }}' || exit_code=$?
          if [[ ${exit_code} -ne 1 ]]; then exit 1; fi
        env:
          whitelist: ''
          dependencies: a,c,d

      - name: Empty depdencencies returns exit 1
        run: |
          bash whitelist-check '${{ env.whitelist }}' ${{ env.dependencies }} || exit_code=$?
          if [[ ${exit_code} -ne 1 ]]; then exit 1; fi
        env:
          whitelist: |-
            a
            b
            c
          dependencies: ''
